# Generated by Django 5.2.5 on 2025-10-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasukuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='title',
            field=models.TextField(default='Tasks', max_length=50),
        ),
    ]
