# Generated by Django 5.2.5 on 2025-10-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasukuapp', '0002_taskstatus_desc_taskstatus_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
