# Generated by Django 5.2.5 on 2025-10-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasukuapp', '0003_alter_taskstatus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(choices=[('To Do', 'Todo'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='To Do', max_length=10),
        ),
    ]
