# Generated by Django 5.2.7 on 2025-11-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasukuapp", "0007_rename_comment_commentmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskstatus",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="taskstatus",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskstatus",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="taskstatus",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
